# ---native
spring:
  cloud:
    config:
      server:
        git:
          search-paths: ymls
          uri: https://github.com/zhfacjy/configFolder.git
#          username: 841018243@qq.com
#          password: zhonghaofa123
      label: master
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769

#management:
#  security:
#    enabled: false